### ISSUE TITLE
Current status of the implementation

### ISSUE THREAD

**Issue by mavam** [rhaist/suricata-json-schema#1]
I was wondering what the current status of the implementation is. It looks like the scaffold to generate test output is there, but I couldn't find anything regarding schema.

I am asking because we're about to start with similar effort and it would be great to avoid duplicate work.

**Comment by rhaist** [comment]
It is a WIP regarding the following ticket in suricata:
https://redmine.openinfosecfoundation.org/issues/2699

I planed to use docker to generate every possible JSON output and translate the eve json line to a schema using https://pypi.org/project/genson/

**Comment by mavam** [comment]
Okay, looking forward to test whatever you have!

We're planning to use the schema with [VAST](https://github.com/vast-io/vast), which is a richer data model than plain JSON. For example, we differentiate IP addresses from strings. Are you also planning to incorporate such semantics?
